name: app_01_todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  get:
  hive:
  svg_flutter: ^0.0.1
  tabler_icons: ^2.5.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/